pre-release-commit-message = "chore: Release gen-bsky v{{version}}"
tag-message = "{{tag_name}}"
tag-name = "gen-bsky-v{{version}}"
pre-release-hook = ["./release-hook.sh"]
pre-release-replacements = []
