pre-release-commit-message = "chore: Release gen-linkedin v{{version}}"
tag-message = "{{tag_name}}"
tag-name = "gen-linkedin-v{{version}}"
pre-release-hook = ["./release-hook.sh"]
pre-release-replacements = []
